### ISSUE TITLE
How to download entire time step in single model run through S3?

### ISSUE THREAD

**Issue by uruz7b3128** [MetOffice/aws-earth-examples#9]
Hello:

I have a high interest in "Met Office Global Atmospheric Hi-Res Model - 10km Deterministic" released on AWS Open data platform.  However, while I reviewed data on S3 bucket, I was confused by file categorized. Seemed data was named by random characters. I tried to comprehend what involved in one file, but I guess it only single time step be released instead of whole forecast time.

Leon

**Comment by jacobtomlinson** [comment]
Thanks for the interest! Currently the data is made available via a pub/sub model due to the volume and velocity of the data we produce (~100k files / ~7TB per day). So you need to subscribe to a notification topic which will alert you to new files as they are created. These notifications will contain metadata about what each file contains so you can do the appropriate filtering to load only the files you require.

Please see the [example notebooks](https://github.com/MetOffice/aws-earth-examples/blob/master/examples/1.%20Getting%20Started.ipynb) to get started.

**Comment by uruz7b3128** [comment]
Thanks for your comments. 
I would check and recast if I want to raise another issue.

**Comment by jacobtomlinson** [comment]
Please don't hesitate to ask more questions in future!
